.class public final Ly8/b$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Ly8/b;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# direct methods
.method public static a(Ly8/b;I)[Ljava/lang/Object;
    .locals 0
    .param p0    # Ly8/b;
        .annotation build Loa/d;
        .end annotation
    .end param
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Ly8/b<",
            "TT;>;I)[TT;"
        }
    .end annotation

    .annotation build Loa/d;
    .end annotation

    new-instance p0, Lkotlin/k0;

    const-string p1, "Generated by Android Extensions automatically"

    invoke-direct {p0, p1}, Lkotlin/k0;-><init>(Ljava/lang/String;)V

    throw p0
.end method
